apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest  # Public image from Docker Hub
        ports:
        - containerPort: 80  # Default port for nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 8087          # Service port within the cluster
    targetPort: 80    # Container port
    nodePort: 30080   # Node port for external access (optional)
  type: NodePort      # NodePort to make the service accessible on a port across all nodes
